### ISSUE TITLE
How to add a datadog.yaml configuration file?

### ISSUE THREAD

**Issue by jeffblake** [DataDog/heroku-buildpack-datadog#184]
Basic question, how do I add an agent configuration file?

I'm trying to integrate Sidekiq and need to add:

```
# dogstatsd_mapper_cache_size: 1000  # default to 1000
dogstatsd_mapper_profiles:
  - name: sidekiq
    prefix: "sidekiq."
    mappings:
      - match: "sidekiq.sidekiq.*"
        name: "sidekiq.*"
      - match: "sidekiq.jobs.*.perform"
        name: "sidekiq.jobs.perform"
        tags:
          worker: "$1"
```

to the agent `datadog.yaml` configuration file. Looking at the run script, it doesn't appear to be possible?
