### ISSUE TITLE
Setting `DD_USE_HEROKU_POSTGRES` does not result in Database Monitoring

### ISSUE THREAD

**Issue by nertzy** [DataDog/heroku-buildpack-datadog#335]
I have set the new `DD_USE_HEROKU_POSTGRES` variable on my deployment.

When I run `agent-wrapper status` via `heroku ps:exec`, I see:

```
    postgres (13.4.0)
    -----------------
      Instance ID: postgres:[REDACTED] [OK]
      Configuration Source: file:/app/.apt/etc/datadog-agent/conf.d/postgres.d/conf.yaml
      Total Runs: 45
      Metric Samples: Last Run: 105, Total: 4,725
      Events: Last Run: 0, Total: 0
      Service Checks: Last Run: 1, Total: 45
      Average Execution Time : 15ms
      Last Execution Date : 2023-05-08 21:59:08 UTC (1683583148000)
      Last Successful Execution Date : 2023-05-08 21:59:08 UTC (1683583148000)
      metadata:
        resolved_hostname: [REDACTED].web.1
        version.major: 15
        version.minor: 2
        version.patch: 0
        version.raw: 15.2 (Ubuntu 15.2-1.pgdg20.04+1)
        version.scheme: semver
```

Those timestamps are current. Everything looks good like it should be running.

But when I go to [APM > Database Monitoring](https://app.datadoghq.com/databases/list) in the Datadog interface, nothing shows up.

Here is the generated `/app/.apt/etc/datadog-agent/conf.d/postgres.d/conf.yaml` file:

```yaml
init_config:

instances:

  - host: ec2-[REDACTED].compute-1.amazonaws.com
    username: datadog
    password: [REDACTED]
    port: 5432
    dbname: [REDACTED]
    ssl: True
    disable_generic_tags: false
```

I noticed that the instance does not contain `dbm: true`. Is this why nothing is showing up for me? Is there a way to enable this?
